sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
branches:
  only:
    - master
    - develop
addons:
  apt:
    packages:
    - python-dev
    - libblas-dev
    - liblapack-dev
    - libatlas-dev
    - gfortran
    - build-essential
install:
  - "travis_wait pip install -r requirements.txt"
script: nosetests tests

